<?php

use Illuminate\Database\Seeder;

class ProfilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('profiles')->delete();
        
        \DB::table('profiles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 9,
                'theme_id' => 288,
                'location' => NULL,
                'company' => 'Home',
                'address' => 'NY',
                'city' => 'NY',
                'avatar' => '/upload/profile/1588267969j70PHr2cri.jpg',
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.png',
                'created_at' => '2020-04-30 20:32:49',
                'updated_at' => '2020-04-30 17:32:49',
                'state' => 'NY',
                'zipcode' => '10365',
                'country' => 'US',
                'billing_address' => 'NY',
                'billing_city' => 'NY',
                'billing_state' => 'NY',
                'billing_zipcode' => '10365',
                'billing_country' => 'US',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 2,
                'theme_id' => 1,
                'location' => NULL,
                'company' => NULL,
                'address' => NULL,
                'city' => NULL,
                'avatar' => '',
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => '2020-04-28 17:10:49',
                'updated_at' => '2020-04-28 17:10:49',
                'state' => NULL,
                'zipcode' => NULL,
                'country' => NULL,
                'billing_address' => NULL,
                'billing_city' => NULL,
                'billing_state' => NULL,
                'billing_zipcode' => NULL,
                'billing_country' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 1,
                'theme_id' => NULL,
                'location' => NULL,
                'company' => NULL,
                'address' => NULL,
                'city' => NULL,
                'avatar' => '',
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => '2020-04-28 17:10:55',
                'updated_at' => '2020-04-28 17:10:55',
                'state' => NULL,
                'zipcode' => NULL,
                'country' => NULL,
                'billing_address' => NULL,
                'billing_city' => NULL,
                'billing_state' => NULL,
                'billing_zipcode' => NULL,
                'billing_country' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 3,
                'theme_id' => NULL,
                'location' => NULL,
                'company' => NULL,
                'address' => NULL,
                'city' => NULL,
                'avatar' => NULL,
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
                'state' => NULL,
                'zipcode' => NULL,
                'country' => NULL,
                'billing_address' => NULL,
                'billing_city' => NULL,
                'billing_state' => NULL,
                'billing_zipcode' => NULL,
                'billing_country' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 4,
                'theme_id' => NULL,
                'location' => NULL,
                'company' => NULL,
                'address' => NULL,
                'city' => NULL,
                'avatar' => NULL,
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
                'state' => NULL,
                'zipcode' => NULL,
                'country' => NULL,
                'billing_address' => NULL,
                'billing_city' => NULL,
                'billing_state' => NULL,
                'billing_zipcode' => NULL,
                'billing_country' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 5,
                'theme_id' => NULL,
                'location' => NULL,
                'company' => NULL,
                'address' => NULL,
                'city' => NULL,
                'avatar' => NULL,
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
                'state' => NULL,
                'zipcode' => NULL,
                'country' => NULL,
                'billing_address' => NULL,
                'billing_city' => NULL,
                'billing_state' => NULL,
                'billing_zipcode' => NULL,
                'billing_country' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 6,
                'theme_id' => NULL,
                'location' => NULL,
                'company' => NULL,
                'address' => NULL,
                'city' => NULL,
                'avatar' => NULL,
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
                'state' => NULL,
                'zipcode' => NULL,
                'country' => NULL,
                'billing_address' => NULL,
                'billing_city' => NULL,
                'billing_state' => NULL,
                'billing_zipcode' => NULL,
                'billing_country' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 7,
                'theme_id' => NULL,
                'location' => NULL,
                'company' => NULL,
                'address' => NULL,
                'city' => NULL,
                'avatar' => NULL,
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
                'state' => NULL,
                'zipcode' => NULL,
                'country' => NULL,
                'billing_address' => NULL,
                'billing_city' => NULL,
                'billing_state' => NULL,
                'billing_zipcode' => NULL,
                'billing_country' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 8,
                'theme_id' => NULL,
                'location' => NULL,
                'company' => NULL,
                'address' => NULL,
                'city' => NULL,
                'avatar' => NULL,
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
                'state' => NULL,
                'zipcode' => NULL,
                'country' => NULL,
                'billing_address' => NULL,
                'billing_city' => NULL,
                'billing_state' => NULL,
                'billing_zipcode' => NULL,
                'billing_country' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 10,
                'theme_id' => NULL,
                'location' => NULL,
                'company' => NULL,
                'address' => NULL,
                'city' => NULL,
                'avatar' => NULL,
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => NULL,
                'updated_at' => NULL,
                'state' => NULL,
                'zipcode' => NULL,
                'country' => NULL,
                'billing_address' => NULL,
                'billing_city' => NULL,
                'billing_state' => NULL,
                'billing_zipcode' => NULL,
                'billing_country' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 13,
                'theme_id' => 1,
                'location' => NULL,
                'company' => '1',
                'address' => 'a',
                'city' => 'b',
                'avatar' => NULL,
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => '2020-04-29 06:28:57',
                'updated_at' => '2020-04-29 06:28:57',
                'state' => 'c',
                'zipcode' => '12345',
                'country' => 'US',
                'billing_address' => 'a',
                'billing_city' => 'b',
                'billing_state' => 'c',
                'billing_zipcode' => '12345',
                'billing_country' => 'US',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 14,
                'theme_id' => 1,
                'location' => NULL,
                'company' => '1',
                'address' => 'a',
                'city' => 'b',
                'avatar' => NULL,
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => '2020-04-29 06:49:25',
                'updated_at' => '2020-04-29 06:49:25',
                'state' => 'c',
                'zipcode' => '12345',
                'country' => 'US',
                'billing_address' => 'a',
                'billing_city' => 'b',
                'billing_state' => 'c',
                'billing_zipcode' => '12345',
                'billing_country' => 'US',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 16,
                'theme_id' => 1,
                'location' => NULL,
                'company' => '1',
                'address' => 'a',
                'city' => '2',
                'avatar' => NULL,
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => '2020-04-29 07:05:12',
                'updated_at' => '2020-04-29 07:05:12',
                'state' => '3',
                'zipcode' => '12345',
                'country' => 'US',
                'billing_address' => 'a',
                'billing_city' => '2',
                'billing_state' => '3',
                'billing_zipcode' => '12345',
                'billing_country' => 'US',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 17,
                'theme_id' => 1,
                'location' => NULL,
                'company' => '1',
                'address' => 'a',
                'city' => 'b',
                'avatar' => '/upload/profile/1588164801jCHsCuUzlI.jpg',
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => '2020-04-29 15:53:21',
                'updated_at' => '2020-04-29 12:53:21',
                'state' => 'c',
                'zipcode' => '12345',
                'country' => 'US',
                'billing_address' => 'a',
                'billing_city' => 'b',
                'billing_state' => 'c',
                'billing_zipcode' => '12345',
                'billing_country' => 'US',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 18,
                'theme_id' => 1,
                'location' => NULL,
                'company' => '2',
                'address' => '1',
                'city' => '2',
                'avatar' => '/upload/profile/1588164009vjcyMzdO63.jpg',
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => '2020-04-29 15:40:09',
                'updated_at' => '2020-04-29 12:40:09',
                'state' => '3',
                'zipcode' => '12345',
                'country' => 'US',
                'billing_address' => '1',
                'billing_city' => '2',
                'billing_state' => '3',
                'billing_zipcode' => '12345',
                'billing_country' => 'US',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 20,
                'theme_id' => 1,
                'location' => NULL,
                'company' => '1',
                'address' => 'test123',
                'city' => 'test123',
                'avatar' => '/upload/profile/1588163524gp28SNXzaM.jpg',
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => '2020-04-29 15:32:04',
                'updated_at' => '2020-04-29 12:32:04',
                'state' => 'test123',
                'zipcode' => '12345',
                'country' => 'United States',
                'billing_address' => 'test123',
                'billing_city' => 'test123',
                'billing_state' => 'test123',
                'billing_zipcode' => '12345',
                'billing_country' => 'United States',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 21,
                'theme_id' => 1,
                'location' => NULL,
                'company' => '5',
                'address' => 'test4',
                'city' => 'test4',
                'avatar' => '/upload/profile/1588271175PjVCs71UVY.jpg',
                'avatar_status' => '0',
                'user_profile_bg' => '/assets/img/default-user-bg.jpg',
                'created_at' => '2020-04-30 18:26:15',
                'updated_at' => '2020-04-30 18:26:15',
                'state' => 'test4',
                'zipcode' => '123456',
                'country' => 'test4',
                'billing_address' => 'test4',
                'billing_city' => 'test4',
                'billing_state' => 'test4',
                'billing_zipcode' => '123456',
                'billing_country' => 'test4',
            ),
        ));
        
        
    }
}