<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'email' => 'jack422@gmail.com',
                'password' => '2fb54875d166ab45a6a8b21f1631dec573a8cf07',
                'company_id' => 1,
                'first_name' => 'Jack',
                'last_name' => 'Fruin',
                'created_at' => '2020-04-27 19:48:09',
                'updated_at' => '2020-04-27 19:48:32',
                'remember_token' => NULL,
                'activated' => 1,
                'token' => 'LfaF0OEX6xGim6yMTtwDoiAFXBnuASlcCsKRihcIKLqEoxB6jVhClcAJc7pYb3Qu',
                'signup_ip_address' => NULL,
                'signup_confirmation_ip_addresss' => NULL,
                'signup_sm_ip_address' => NULL,
                'admin_ip_address' => NULL,
                'updated_ip_address' => NULL,
                'deleted_ip_address' => NULL,
                'last_chat_id' => NULL,
                'online_state' => NULL,
                'name' => 'user1',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'email' => 'jane623@gmail.com',
                'password' => NULL,
                'company_id' => 2,
                'first_name' => 'Jane',
                'last_name' => 'Ross',
                'created_at' => '2020-04-27 19:48:14',
                'updated_at' => '2020-04-27 19:48:35',
                'remember_token' => NULL,
                'activated' => 1,
                'token' => 'XfFjSeTGKGlrApVS7UfCbilg91VqfeIWbP2Qgm1wJ7UyucUGBS3B7fmEhz0OiLWZ',
                'signup_ip_address' => NULL,
                'signup_confirmation_ip_addresss' => NULL,
                'signup_sm_ip_address' => NULL,
                'admin_ip_address' => NULL,
                'updated_ip_address' => NULL,
                'deleted_ip_address' => NULL,
                'last_chat_id' => NULL,
                'online_state' => NULL,
                'name' => 'user2',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'email' => 'tom853@gmail.com',
                'password' => NULL,
                'company_id' => 1,
                'first_name' => 'Tom',
                'last_name' => 'Dawson',
                'created_at' => '2020-04-27 19:48:19',
                'updated_at' => '2020-04-27 19:48:37',
                'remember_token' => NULL,
                'activated' => 1,
                'token' => 'iot2YWbzeIHGcQS0v8LOVon3GEUOdnkk0UrKZLXHnCu63Ftij7z0wZKsImDBBe3m',
                'signup_ip_address' => NULL,
                'signup_confirmation_ip_addresss' => NULL,
                'signup_sm_ip_address' => NULL,
                'admin_ip_address' => NULL,
                'updated_ip_address' => NULL,
                'deleted_ip_address' => NULL,
                'last_chat_id' => NULL,
                'online_state' => NULL,
                'name' => 'user3',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'email' => 'billy753@gmail.com',
                'password' => NULL,
                'company_id' => 2,
                'first_name' => 'Billy',
                'last_name' => 'Kate',
                'created_at' => '2020-04-27 19:48:22',
                'updated_at' => '2020-04-27 19:48:40',
                'remember_token' => NULL,
                'activated' => 1,
                'token' => 'wb2qriUtxyJUFkEUeuypylW6VU4xJ7NJKw5G9Udi0hVQtCrpxAp4frzvVH5Lde3p',
                'signup_ip_address' => NULL,
                'signup_confirmation_ip_addresss' => NULL,
                'signup_sm_ip_address' => NULL,
                'admin_ip_address' => NULL,
                'updated_ip_address' => NULL,
                'deleted_ip_address' => NULL,
                'last_chat_id' => NULL,
                'online_state' => NULL,
                'name' => 'user4',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'email' => 'max428@gmail.com',
                'password' => NULL,
                'company_id' => 1,
                'first_name' => 'Max',
                'last_name' => 'Houston',
                'created_at' => '2020-04-27 19:48:24',
                'updated_at' => '2020-04-27 19:48:42',
                'remember_token' => NULL,
                'activated' => 1,
                'token' => 'pFURzHtFJyfnHIPsn40T0aDPSrwoEe5WxnMwJ12ISwRWZLT43ZdgegvAP40Jgmrx',
                'signup_ip_address' => NULL,
                'signup_confirmation_ip_addresss' => NULL,
                'signup_sm_ip_address' => NULL,
                'admin_ip_address' => NULL,
                'updated_ip_address' => NULL,
                'deleted_ip_address' => NULL,
                'last_chat_id' => NULL,
                'online_state' => NULL,
                'name' => 'user5',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'email' => 'jin716@gmail.com',
                'password' => NULL,
                'company_id' => 2,
                'first_name' => 'Jin',
                'last_name' => 'William',
                'created_at' => '2020-04-27 19:48:27',
                'updated_at' => '2020-04-27 19:48:44',
                'remember_token' => NULL,
                'activated' => 1,
                'token' => 'NHdukQHS04DOFOFWHInVgDjTFQxOgig5YFvR5o5CcPToD0hPaWq4aXnJAyGvnZlq',
                'signup_ip_address' => NULL,
                'signup_confirmation_ip_addresss' => NULL,
                'signup_sm_ip_address' => NULL,
                'admin_ip_address' => NULL,
                'updated_ip_address' => NULL,
                'deleted_ip_address' => NULL,
                'last_chat_id' => NULL,
                'online_state' => NULL,
                'name' => 'user6',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'email' => 'joe826@gmail.com',
                'password' => NULL,
                'company_id' => 1,
                'first_name' => 'Joe',
                'last_name' => 'Roach',
                'created_at' => '2020-04-27 19:48:29',
                'updated_at' => '2020-04-27 19:48:46',
                'remember_token' => NULL,
                'activated' => 1,
                'token' => 'zyEgCQQ2tqcRAYFlweYu1l3UOcusjaJlN1IouLEFInp66brup94jVNdvmK4d7QLe',
                'signup_ip_address' => NULL,
                'signup_confirmation_ip_addresss' => NULL,
                'signup_sm_ip_address' => NULL,
                'admin_ip_address' => NULL,
                'updated_ip_address' => NULL,
                'deleted_ip_address' => NULL,
                'last_chat_id' => NULL,
                'online_state' => NULL,
                'name' => 'user7',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'email' => 'aaa@aaa.com',
                'password' => 'a95fe5d3cf46ef9607102b3fdbc15c2756db794c',
                'company_id' => 1,
                'first_name' => 'Judy',
                'last_name' => 'Han',
                'created_at' => '2020-03-27 06:51:06',
                'updated_at' => '2020-03-27 06:51:06',
                'remember_token' => NULL,
                'activated' => 1,
                'token' => 'OXxCTTISLUmqs8AoWULb5O5rQ9u7uLpbq20rGFSV5Hq2tEelxMXfbvvQyERKfoma',
                'signup_ip_address' => NULL,
                'signup_confirmation_ip_addresss' => NULL,
                'signup_sm_ip_address' => NULL,
                'admin_ip_address' => NULL,
                'updated_ip_address' => NULL,
                'deleted_ip_address' => NULL,
                'last_chat_id' => NULL,
                'online_state' => NULL,
                'name' => 'user8',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'email' => 'user@user.com',
                'password' => '$2y$10$rhtDTIHmrBDd2MMbySlwcOHNkXxsJ14H5F5TDNrCvR0nz/jmbU3r6',
                'company_id' => NULL,
                'first_name' => 'User',
                'last_name' => 'user',
                'created_at' => '2020-04-27 14:17:05',
                'updated_at' => '2020-04-30 17:32:49',
                'remember_token' => 'wL4S6n3Qnst3YgJDjmEVHDuVR3mP65xg0C0RJCWtr8E9o86O5fZE4EjlTBfj',
                'activated' => 1,
                'token' => 'nMQAt56hHnxnobZpVVf9eLShM4jPHDrJkgmjgNQdAjBNVMs3X7ISmYXPX9oghI01',
                'signup_ip_address' => '0.0.0.0',
                'signup_confirmation_ip_addresss' => NULL,
                'signup_sm_ip_address' => NULL,
                'admin_ip_address' => NULL,
                'updated_ip_address' => NULL,
                'deleted_ip_address' => NULL,
                'last_chat_id' => NULL,
                'online_state' => NULL,
                'name' => 'user123',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'email' => 'admin@admin.com',
                'password' => '$2y$10$a3I6EPdwZJz/23MSE.Tsn.BOkXLNIZTwRZceoYOMlqDZXEU9PVhLq',
                'company_id' => 2,
                'first_name' => 'Admin',
                'last_name' => 'admin',
                'created_at' => '2020-04-27 19:56:13',
                'updated_at' => '2020-04-27 19:56:13',
                'remember_token' => NULL,
                'activated' => 1,
                'token' => 'Bt1u9evtGkMmZs10nvzt4DcsVYWYdLrb74rh0PRb5dzdUDCmdzTOg9z6VJWqxTV7',
                'signup_ip_address' => '0.0.0.0',
                'signup_confirmation_ip_addresss' => NULL,
                'signup_sm_ip_address' => NULL,
                'admin_ip_address' => NULL,
                'updated_ip_address' => NULL,
                'deleted_ip_address' => NULL,
                'last_chat_id' => NULL,
                'online_state' => NULL,
                'name' => 'Admin123',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 14,
                'email' => 'tester2@test.com',
                'password' => '$2y$10$/Qq3yhtFoeQOsIehpKbh1uCtDzDxVTsj1v/03LOjq9GVG5xLCHQLu',
                'company_id' => 2,
                'first_name' => 'tester2',
                'last_name' => 'tester2',
                'created_at' => '2020-04-29 06:49:25',
                'updated_at' => '2020-04-29 06:49:25',
                'remember_token' => NULL,
                'activated' => 1,
                'token' => 'UkiQH8MqjAlfvVEf032J9CZNu64S9aTYVM341ziWuezEVSOZMoRIrVAIBchoqfGo',
                'signup_ip_address' => NULL,
                'signup_confirmation_ip_addresss' => NULL,
                'signup_sm_ip_address' => NULL,
                'admin_ip_address' => '0.0.0.0',
                'updated_ip_address' => NULL,
                'deleted_ip_address' => NULL,
                'last_chat_id' => NULL,
                'online_state' => NULL,
                'name' => 'tester1234',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 17,
                'email' => 'test3@test.com',
                'password' => '$2y$10$fmvZKw2S8on.q9hbZv6WKey/Ia7.D9BqVxrfApDacPlA6/vg1jm9i',
                'company_id' => 1,
                'first_name' => 'test3',
                'last_name' => 'test3',
                'created_at' => '2020-04-29 07:10:12',
                'updated_at' => '2020-04-29 12:53:21',
                'remember_token' => NULL,
                'activated' => 1,
                'token' => 't1l0wH8fE87nmuB9kfrYeVllz9mnLNrBP1oc6uYNpPQHESxUdZqX0ZPR363S71tc',
                'signup_ip_address' => NULL,
                'signup_confirmation_ip_addresss' => NULL,
                'signup_sm_ip_address' => NULL,
                'admin_ip_address' => '0.0.0.0',
                'updated_ip_address' => '0.0.0.0',
                'deleted_ip_address' => NULL,
                'last_chat_id' => NULL,
                'online_state' => NULL,
                'name' => 'test3',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 18,
                'email' => 'test4@test.com',
                'password' => '$2y$10$hHi860OpyfypR.lmHUk54eXsCaIpu5JJqcEJqVSDGNqTaC/x14pEK',
                'company_id' => 2,
                'first_name' => 'test4',
                'last_name' => 'test4',
                'created_at' => '2020-04-29 08:01:32',
                'updated_at' => '2020-04-29 12:40:09',
                'remember_token' => NULL,
                'activated' => 1,
                'token' => 'TnbmrDfMVHwRVlKx2OtstGx0WeERWFLHdyy3LfGVJtogm72wdcAbeuvqe9DeSaUa',
                'signup_ip_address' => NULL,
                'signup_confirmation_ip_addresss' => NULL,
                'signup_sm_ip_address' => NULL,
                'admin_ip_address' => '0.0.0.0',
                'updated_ip_address' => '0.0.0.0',
                'deleted_ip_address' => NULL,
                'last_chat_id' => NULL,
                'online_state' => NULL,
                'name' => 'test4',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 20,
                'email' => 'test123@test.com',
                'password' => '$2y$10$B.hR/AOOEj1b.jtPCV2PnOOOlm172HAeJ8LgjyOWlCdsMdMHNGqCS',
                'company_id' => 1,
                'first_name' => 'test123',
                'last_name' => 'test123',
                'created_at' => '2020-04-29 12:18:43',
                'updated_at' => '2020-04-29 12:32:04',
                'remember_token' => NULL,
                'activated' => 1,
                'token' => 'XO6xlH2i4COK88mASaVxRrFLqpwnWHVrz6JLhbaUjjB3Buznc2XwQP3S5scfgzD4',
                'signup_ip_address' => NULL,
                'signup_confirmation_ip_addresss' => NULL,
                'signup_sm_ip_address' => NULL,
                'admin_ip_address' => '0.0.0.0',
                'updated_ip_address' => '0.0.0.0',
                'deleted_ip_address' => NULL,
                'last_chat_id' => NULL,
                'online_state' => NULL,
                'name' => 'test123',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 21,
                'email' => 'test4@test4.com',
                'password' => '$2y$10$7arEpVCNzwVURjCNsQJIIuZHPvFOz3tnU9nr1M/pCNZCVI0scugq2',
                'company_id' => 5,
                'first_name' => 'test4',
                'last_name' => 'test4',
                'created_at' => '2020-04-30 18:26:15',
                'updated_at' => '2020-04-30 18:26:15',
                'remember_token' => NULL,
                'activated' => 1,
                'token' => 'NM32h6nMphshrqlvnroKbVVxO7gKFew048HxIbcmynaGmiQI5PUTFQxifmpUqbKb',
                'signup_ip_address' => NULL,
                'signup_confirmation_ip_addresss' => NULL,
                'signup_sm_ip_address' => NULL,
                'admin_ip_address' => '0.0.0.0',
                'updated_ip_address' => NULL,
                'deleted_ip_address' => NULL,
                'last_chat_id' => NULL,
                'online_state' => NULL,
                'name' => 'test4',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}